# DriveValue AI: Feature Engineering & Data Preprocessing
## Capstone Project
**Author:** Jacqualine Makgolana

## Purpose

The purpose of this notebook is to prepare the cleaned dataset for machine learning.

This includes handling missing values, engineering useful features, encoding categorical variables, scaling numerical features where appropriate, and splitting the data into training and testing datasets. The resulting dataset will be used to train and evaluate regression models that predict used car asking prices.

In [2]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [3]:
df = pd.read_csv("../Data/processed/used_cars_cleaned.csv")

print(df.shape)

df.head()

(14988, 11)

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
0,NaN,NaN,2001.0,23.0,98000.0,NaN,NaN,Unknown,Nov-24,"Honda City v teck in mint condition, valid gen...",195000
1,Toyota,NaN,NaN,15.0,190000.0,Manual,NaN,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...",375000
2,Volkswagen,NaN,2010.0,NaN,NaN,Manual,first,NaN,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...",184999
3,NaN,Swift,2017.0,7.0,NaN,Manual,second,Unknown,NaN,Maruti Suzuki Swift 2017 Diesel Good Condition,565000
4,Maruti Suzuki,NaN,2019.0,5.0,NaN,Automatic,NaN,Unknown,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol",685000

In [4]:
df.isnull().sum().sort_values(ascending=False)

Owner           5329
model           5233
Year            3300
kmDriven        3148
PostedDate      3121
Age             2993
Transmission    2970
Brand           2641
FuelType        2629
AdditionInfo       0
AskPrice           0
dtype: int64

## Handling Missing Values

it is important to identify missing values that may affect model performance. The following analysis identifies columns with incomplete data so that an appropriate imputation strategy can be applied.

In [5]:
df["Brand"] = df["Brand"].fillna("Unknown")
df["model"] = df["model"].fillna("Unknown")
df["Owner"] = df["Owner"].fillna("Unknown")
df["FuelType"] = df["FuelType"].fillna("Unknown")
df["Transmission"] = df["Transmission"].fillna("Unknown")
df["PostedDate"] = df["PostedDate"].fillna("Unknown")

In [6]:
df["Year"] = df["Year"].fillna(df["Year"].median())
df["Age"] = df["Age"].fillna(df["Age"].median())
df["kmDriven"] = df["kmDriven"].fillna(df["kmDriven"].median())

In [7]:
df.isnull().sum()

Brand           0
model           0
Year            0
Age             0
kmDriven        0
Transmission    0
Owner           0
FuelType        0
PostedDate      0
AdditionInfo    0
AskPrice        0
dtype: int64

In [8]:
df = df.drop(columns=["AdditionInfo"])

In [9]:
X = df.drop("AskPrice", axis=1)

y = df["AskPrice"]

In [10]:
X = pd.get_dummies(
    X,
    drop_first=True
)

X.head()

,Year,Age,kmDriven,Brand_Audi,Brand_BMW,Brand_Bajaj,Brand_Bentley,Brand_Chevrolet,Brand_Citroen,Brand_Datsun,...,PostedDate_Dec-24,PostedDate_Jan-24,PostedDate_Jul-24,PostedDate_Jun-24,PostedDate_Mar-24,PostedDate_May-24,PostedDate_Nov-24,PostedDate_Oct-24,PostedDate_Sep-24,PostedDate_Unknown
0,2001.0,23.0,98000.0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1,2017.0,15.0,190000.0,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,2010.0,7.0,65868.5,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,2017.0,7.0,65868.5,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,2019.0,5.0,65868.5,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [11]:
print(X.shape)

X.head()

(14988, 466)

,Year,Age,kmDriven,Brand_Audi,Brand_BMW,Brand_Bajaj,Brand_Bentley,Brand_Chevrolet,Brand_Citroen,Brand_Datsun,...,PostedDate_Dec-24,PostedDate_Jan-24,PostedDate_Jul-24,PostedDate_Jun-24,PostedDate_Mar-24,PostedDate_May-24,PostedDate_Nov-24,PostedDate_Oct-24,PostedDate_Sep-24,PostedDate_Unknown
0,2001.0,23.0,98000.0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1,2017.0,15.0,190000.0,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,2010.0,7.0,65868.5,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,2017.0,7.0,65868.5,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,2019.0,5.0,65868.5,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training:", X_train.shape)
print("Testing :", X_test.shape)

Training: (11990, 466)
Testing : (2998, 466)

In [13]:
X_train.to_csv("../Data/processed/X_train.csv", index=False)

X_test.to_csv("../Data/processed/X_test.csv", index=False)

y_train.to_csv("../Data/processed/y_train.csv", index=False)

y_test.to_csv("../Data/processed/y_test.csv", index=False)

print("Datasets saved successfully!")

Datasets saved successfully!

## Summary

The cleaned dataset was successfully prepared for machine learning.

The preprocessing process included:

- Handling missing values
- Removing unnecessary features
- Encoding categorical variables
- Separating predictor variables from the target variable
- Splitting the dataset into training and testing datasets

The processed datasets are now ready for model development and evaluation in the next notebook.